# Generated by Django 2.0 on 2018-02-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_timeline_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_timeline', to=settings.AUTH_USER_MODEL),
        ),
    ]
