# Generated by Django 2.0 on 2018-02-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_auto_20180223_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='usuario',
        ),
        migrations.AddField(
            model_name='timeline',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_timeline', to='perfis.Perfil'),
        ),
    ]
